import { Playfair_Display } from "next/font/google";
import Image from "next/image";

const playfair = Playfair_Display({
  subsets: ["latin"],
});

export default function Home() {
  return (
    <main className="min-h-screen bg-[#020617] text-white">
      <section className="mx-auto flex min-h-screen max-w-5xl flex-col items-center justify-center px-6 text-center">
        
      <div className="mb-6">
  <Image
    src="/shortlist.svg"
    alt="ShortList Logo"
    width={140}
    height={140}
    priority
    className="drop-shadow-[0_0_25px_rgba(6,182,212,0.25)]"
  />
</div>
        
        <div className="mb-6 rounded-full border border-cyan-400/30 bg-cyan-400/10 px-4 py-2 text-sm text-cyan-300">
          AI-Powered Resume Match Analyzer
        </div>

<h1
  className={`${playfair.className} max-w-3xl text-6xl font-semibold italic tracking-wide text-white drop-shadow-[0_0_25px_rgba(6,182,212,0.35)] md:text-8xl`}
>
  ShortList
</h1>

        <p className="mt-6 max-w-2xl text-lg text-slate-300">
          Analyze your resume against any job description, improve your ATS
          score, identify missing keywords, and generate a stronger resume with
          AI.
        </p>

        <a
          href="/analyzer"
          className="mt-8 rounded-xl bg-cyan-400 px-6 py-3 font-semibold text-slate-950 transition hover:bg-cyan-300"
        >
          Analyze My Resume
        </a>
      </section>

      <section className="mx-auto max-w-6xl px-6 py-20">
        <h2 className="text-center text-3xl font-bold md:text-4xl">
          How It Works
        </h2>

        <div className="mt-10 grid gap-6 md:grid-cols-4">
          {[
            ["1", "Upload or Paste Resume", "Upload a PDF or paste your resume text directly."],
            ["2", "Add Job Description", "Paste the job description you want to apply for."],
            ["3", "Get AI Analysis", "Receive ATS scores, missing keywords, and recruiter feedback."],
            ["4", "Improve Your Resume", "Generate a stronger AI-improved resume draft."],
          ].map(([number, title, desc]) => (
            <div
              key={number}
              className="rounded-2xl border border-slate-800 bg-slate-950 p-6"
            >
              <div className="flex h-10 w-10 items-center justify-center rounded-full bg-cyan-400 font-bold text-slate-950">
                {number}
              </div>
              <h3 className="mt-5 text-lg font-bold">{title}</h3>
              <p className="mt-3 text-sm text-slate-400">{desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-6 py-20">
        <h2 className="text-center text-3xl font-bold md:text-4xl">
          Why Use ShortList?
        </h2>

        <div className="mt-10 grid gap-4 md:grid-cols-3">
          {[
            "ATS Compatibility Score",
            "Missing Keyword Detection",
            "AI Resume Improvements",
            "Smart Line Reviews",
            "Recruiter Verdict",
            "Downloadable PDF Report",
          ].map((feature) => (
            <div
              key={feature}
              className="rounded-xl border border-slate-800 bg-slate-950 p-5 text-slate-300"
            >
              <span className="text-cyan-300">✓</span> {feature}
            </div>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-4xl px-6 py-20 text-center">
        <h2 className="text-3xl font-bold md:text-4xl">
          Ready to improve your resume?
        </h2>

        <p className="mt-4 text-slate-400">
          Match your resume with a job description and get instant AI feedback.
        </p>

        <a
          href="/analyzer"
          className="mt-8 inline-block rounded-xl bg-cyan-400 px-6 py-3 font-semibold text-slate-950 transition hover:bg-cyan-300"
        >
          Start Analyzing
        </a>
      </section>

      <footer className="border-t border-slate-800 py-10">
        <div className="mx-auto max-w-6xl px-6 text-center">
          <p className="text-sm leading-relaxed text-slate-500">
            ShortList provides AI-powered resume analysis, ATS scoring, and
            resume optimization suggestions. Results are generated by artificial
            intelligence and should be reviewed before making employment or
            career decisions.
          </p>

          <div className="mt-6 space-y-2">
            <p className="text-xs text-slate-600">
              © 2026 ShortList. All Rights Reserved.
            </p>

            <p className="text-xs text-slate-600">
              Designed & Developed by Lawrence Saludes.
            </p>
          </div>
        </div>
      </footer>
    </main>
  );
}